TENANT_ID: 62366534-1ec3-4962-8869-9b5535279d0b
SECURITY_TOKEN_SERVICE_REST_URL: https://api-gw.oera.no/security-token-service
LDAP_URL: ldaps://ldapgw.adeo.no
LDAP_BASEDN: dc=adeo,dc=no
LDAP_DOMAIN: ADEO.NO
LDAP_SERVICEUSER_BASEDN: ou=ServiceAccounts,dc=adeo,dc=no
LDAP_USER_BASEDN: ou=NAV,ou=BusinessUnits,dc=adeo,dc=no
