SECURITY_TOKEN_SERVICE_REST_URL: https://security-token-service.nais.preprod.local

FOERSTESIDEGENERATOR_BASE_URL: https://foerstesidegenerator-q1.dev.intern.nav.no/api/foerstesidegenerator/v1/foersteside
