TENANT_ID: 966ac572-f5b7-4bbe-aa88-c76419c0f851
SECURITY_TOKEN_SERVICE_REST_URL: https://security-token-service.nais.preprod.local

FOERSTESIDEGENERATOR_BASE_URL: https://foerstesidegenerator-q1.dev.intern.nav.no/api/foerstesidegenerator/v1/foersteside

KLANKE_BASE_URL: https://wasapp-q1.adeo.no/KlageOgAnke

DOK_DIST_KANAL_URL: https://dokdistkanal-q1.dev.intern.nav.no/rest/bestemDistribusjonskanal
DOK_DIST_KANAL_SCOPE: dev-fss.teamdokumenthandtering.dokdistkanal

SAF_SCOPE: dev-fss.teamdokumenthandtering.saf-q1

