name: Deploy (dev -> e2e -> prod)

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/dependabot.yml'

jobs:
  deploy_to_dev:
    name: Dev
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/deploy-to-dev.yaml
    with:
      e2e_tag: latest

  deploy_to_prod:
    name: Prod
    permissions:
      contents: write
      id-token: write
    needs: deploy_to_dev
    uses: ./.github/workflows/deploy-to-prod.yaml
