name: Deploy (dev -> e2e -> prod)

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/dependabot.yml'

jobs:
  deploy_to_dev:
    name: Dev
    uses: ./.github/workflows/deploy-to-dev.yaml
    with:
      e2e_tag: latest
    secrets:
      NAIS_DEPLOY_API_KEY: ${{ secrets.NAIS_DEPLOY_API_KEY }}
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
  
  deploy_to_prod:
    name: Prod
    needs: deploy_to_dev
    uses: ./.github/workflows/deploy-to-prod.yaml
    secrets:
      NAIS_DEPLOY_API_KEY: ${{ secrets.NAIS_DEPLOY_API_KEY }}
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
